version: '3.8'

services:
  postgres:
    image: postgres:13.0
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
    container_name: health_board_postgres
    environment:
      POSTGRES_DB: health_board_dev
      POSTGRES_USER: health_board
      POSTGRES_PASSWORD: health_board
    volumes:
      - ../../data:/Users/laercios/Projects/OPAS/health_board/.misc/data/
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
    name: health_board_postgres
