version: '3.8'

services:
  health_board:
    image: pydemic/health_board:prod
    restart: unless-stopped
    environment:
      HB__ENDPOINT__HTTPS: 'false'
      HB__ENDPOINT__HOSTNAME: localhost
      HB__ENDPOINT__ORIGIN_HOSTNAMES: '//localhost'
      HB__ENDPOINT__SECRET_KEY_BASE: 'Cd6TFymxTTCv5s3N96AbHsZr7g2TvpRVsM+uG9La9OfNQNaF4yaMhSTmiOBPxmmr'
    ports:
      - 80:80
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0
    restart: unless-stopped
    environment:
      POSTGRES_DB: health_board
      POSTGRES_USER: health_board
      POSTGRES_PASSWORD: health_board
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: health_board_prod_postgres
